openapi: 3.0.1
info:
  title: 'Star Wars '
  description: Star Wars Demo API
  version: '1.0'
servers:
  - url: https://apimaisdemo.azure-api.net/sw
paths:
  /people/:
    get:
      summary: Get People
      description: Gets People Operation Demo
      operationId: get-people
      responses:
        '200':
          description: 
  '/people/{id}':
    get:
      summary: Get People By Id
      description: GETs people by Id Operation demo
      operationId: get-people-by-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: 
  /film:
    get:
      summary: Get Film
      operationId: get-film
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                count: 1
                films:
                  - title: A New Hope
                    release-date: '1977-05-25'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]