openapi: 3.0.1
info:
  title: Service Bus Operations
  version: '1.0'
servers:
  - url: https://apim-wkshp-ais.azure-api.net/sb-operations
paths:
  '/{queue_or_topic}':
    post:
      summary: Send Message
      operationId: send-message
      parameters:
        - name: queue_or_topic
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]